### ISSUE TITLE
The model can be loaded only with a certain version of torch (ModuleNotFoundError: No module named 'torch.torch_version')

### ISSUE THREAD

**Issue by iliaNecrov** [flairNLP/flair#2687] opened 2022-03-23 20:38 UTC
I have trained a NER model with using
```
flair==0.10
torch==1.10.0
```
Then I tried:
```
model = SequenceTagger.load('model.pt')
```

> 2022-03-23 23:20:30,810 loading file model.pt

It worked okay, but...

After I tried to load it from another device, where I had
```
flair==0.10
torch==1.9.1 or torch==1.7.0
```
```
model = SequenceTagger.load('model.pt')
```

> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-6-fbd7ba4c5096> in <module>
> ----> 1 model = SequenceTagger.load('model.pt')
> 
> ~\anaconda3\lib\site-packages\flair\nn\model.py in load(cls, model)
>     131             # see https://github.com/zalandoresearch/flair/issues/351
>     132             f = file_utils.load_big_file(str(model_file))
> --> 133             state = torch.load(f, map_location='cpu')
>     134 
>     135         model = cls._init_model_with_state_dict(state)
> 
> ~\anaconda3\lib\site-packages\torch\serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
>     605                     opened_file.seek(orig_position)
>     606                     return torch.jit.load(opened_file)
> --> 607                 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
>     608         return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
>     609 
> 
> ~\anaconda3\lib\site-packages\torch\serialization.py in _load(zip_file, map_location, pickle_module, pickle_file, **pickle_load_args)
>     880     unpickler = UnpicklerWrapper(data_file, **pickle_load_args)
>     881     unpickler.persistent_load = persistent_load
> --> 882     result = unpickler.load()
>     883 
>     884     torch._utils._validate_loaded_sparse_tensors()
> 
> ~\anaconda3\lib\site-packages\torch\serialization.py in find_class(self, mod_name, name)
>     873         def find_class(self, mod_name, name):
>     874             mod_name = load_module_mapping.get(mod_name, mod_name)
> --> 875             return super().find_class(mod_name, name)
>     876 
>     877     # Load the data (which may in turn use `persistent_load` to load tensors)
> 
> ModuleNotFoundError: No module named 'torch.torch_version'

I don’t know if this is normal, but I would like to clarify if I made a mistake somewhere or if this is a bug.

**Comment by iliaNecrov** [comment] 2022-03-23 20:48
https://drive.google.com/file/d/1NxSw62QxQhv4gPWaXX9Gs6EYYZOPhsf7/view?usp=sharing 

Attaching my model

**Comment by alanakbik** [comment] 2022-03-24 09:59
@iliaNecrov thanks for reporting this! I think this could be a problem in backwards compatibility in torch and not so much a flair issue. @aynetdia could you look into this?

**Comment by iliaNecrov** [comment] 2022-03-24 10:56
@alanakbik You are welcom! I have already faced some additional issues (memory errors) with torch==1.10.0. 
And as it turns out, I'm not the only one..
https://github.com/pytorch/pytorch/issues/67680

**Comment by aynetdia** [comment] 2022-03-24 18:43
@iliaNecrov I have looked into this and was able to replicate the issue. Using `torch==1.9.1 or torch==1.7.0` to load the linked model raises the aforementioned error for me as well. Meanwhile `torch==1.10.0 or torch==1.11.0` works fine. 

To me it also seems that the issue is caused by backwards compatibility problems on PyTorch's side, as @alanakbik mentioned. Flair implements the [recommended way](https://pytorch.org/tutorials/recipes/recipes/saving_and_loading_models_for_inference.html#introduction) to save and load PyTorch models, however PyTorch themselves warn that incompatibility issues may nevertheless arise due to how the `pickle` module works - [here](https://pytorch.org/tutorials/recipes/recipes/saving_and_loading_models_for_inference.html#introduction) and [here](https://pytorch.org/docs/stable/notes/serialization.html#saving-and-loading-scriptmodules-across-pytorch-versions).

**Comment by alanakbik** [comment] 2022-03-25 08:35
@aynetdia thanks for looking into this! I guess in this case the best course of action would be to use the same torch version as before. Closing this issue, but feel free to reopen if there's more to discuss!

**Closed by alanakbik** 2022-03-25 08:35 UTC
Labels: bug
