### ISSUE TITLE
Building a Spelling Corrector using a flair character level language model 

### ISSUE THREAD

**Issue by Wickky** [flairNLP/flair#1594] opened 2020-05-08 15:08 UTC
I would like to develop a **spelling corrector** in my own language. I have tried the following methods and I am facing difficulties.
1. Using **encoder decoder with attention** as in **Machine Translation Tasks**. But this produces **very bad outputs** even with the **correct** tokens and this method cannot handle **very long** sequences well although it works with **short** sequences.
2. Using some **edit distance calculations** to get the candidates of the wrong tokens and using language model to find the appropriate correct token for that sequence. But this method does not cover as much as I expected.
So I would like to know if I can use a **character level language model** for the **Spelling Corrector** task. 
I saw a decent character level language model can be trained using Flair. 
If there is **any ideas apart from this** would be appreciated. 
I hope someone can help me for this.
Thanks in advance!

**Comment by alanakbik** [comment] 2020-05-11 16:54
Duplicate of #1575

**Closed by alanakbik** 2020-05-11 16:54 UTC
Labels: question
