### ISSUE TITLE
Unable to pip3 install flair --error on sentencepiece

### ISSUE THREAD

**Issue by MariaLuisaCroci** [flairNLP/flair#2969] opened 2022-10-25 15:38 UTC
I tried in a jupyter notebook to install the library as ```!pip3 install flair```. 

However, after several requirements already satisfied, this error is returned:

```Building wheels for collected packages: sentencepiece
  Building wheel for sentencepiece (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-310
      creating build/lib.macosx-10.9-universal2-cpython-310/sentencepiece
      copying src/sentencepiece/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/sentencepiece
      copying src/sentencepiece/sentencepiece_model_pb2.py -> build/lib.macosx-10.9-universal2-cpython-310/sentencepiece
      copying src/sentencepiece/sentencepiece_pb2.py -> build/lib.macosx-10.9-universal2-cpython-310/sentencepiece
      running build_ext
      /bin/sh: pkg-config: command not found
      Cloning into 'sentencepiece'...
      Note: switching to '0e6dfbf86e2fa6d86a3d9a8a08a628da71c073e0'.
      
      You are in 'detached HEAD' state. You can look around, make experimental
      changes and commit them, and you can discard any commits you make in this
      state without impacting any branches by switching back to a branch.
      
      If you want to create a new branch to retain commits you create, you may
      do so (now or later) by using -c with the switch command. Example:
      
        git switch -c <new-branch-name>
      
      Or undo this operation with:
      
        git switch -
      
      Turn off this advice by setting config variable advice.detachedHead to false
      
      ./build_bundled.sh: line 15: cmake: command not found
      ./build_bundled.sh: line 16: nproc: command not found
      make: *** No targets specified and no makefile found.  Stop.
      make: *** No rule to make target 'install'.  Stop.
      env: pkg-config: No such file or directory
      Failed to find sentencepiece pkg-config
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for sentencepiece
  Running setup.py clean for sentencepiece
Failed to build sentencepiece
Installing collected packages: sentencepiece, pptree, more-itertools, conllu, wikipedia-api, gdown, flair
  Attempting uninstall: sentencepiece
    Found existing installation: sentencepiece 0.1.97
    Uninstalling sentencepiece-0.1.97:
      Successfully uninstalled sentencepiece-0.1.97
  Running setup.py install for sentencepiece ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for sentencepiece did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      running install
      /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-310
      creating build/lib.macosx-10.9-universal2-cpython-310/sentencepiece
      copying src/sentencepiece/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/sentencepiece
      copying src/sentencepiece/sentencepiece_model_pb2.py -> build/lib.macosx-10.9-universal2-cpython-310/sentencepiece
      copying src/sentencepiece/sentencepiece_pb2.py -> build/lib.macosx-10.9-universal2-cpython-310/sentencepiece
      running build_ext
      /bin/sh: pkg-config: command not found
      mkdir: bundled: File exists
      fatal: destination path 'sentencepiece' already exists and is not an empty directory.
      fatal: destination path 'sentencepiece' already exists and is not an empty directory.
      mkdir: build: File exists
      ./build_bundled.sh: line 15: cmake: command not found
      ./build_bundled.sh: line 16: nproc: command not found
      make: *** No targets specified and no makefile found.  Stop.
      make: *** No rule to make target 'install'.  Stop.
      env: pkg-config: No such file or directory
      Failed to find sentencepiece pkg-config
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of sentencepiece
  Moving to /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sentencepiece-0.1.97.dist-info/
   from /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/~entencepiece-0.1.97.dist-info
  Moving to /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sentencepiece/
   from /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/~entencepiece
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> sentencepiece

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

```

I'm working on Mac OS, python version '3.10.7'.

I also tried to ```pip3 install sentencepiece``` and this works fine, but flair library doesn't work yet.

**Comment by alanakbik** [comment] 2022-10-25 15:48
Hello @MariaLuisaCroci, this could be because of the python version used. Could you try with 3.7?

We are currently testing with 3.7, but you are using 3.10 which is still in "bugfix" stage (https://devguide.python.org/versions/).

**Comment by alanakbik** [comment] 2022-10-25 15:50
@MariaLuisaCroci I just see this is a duplicate of #2833 and can be fixed if you install with `pip install git+https://github.com/flairNLP/flair`. Then it should also work with Python 3.10. 

We will release a new Flair version soon so it will work out of the box again.

**Comment by MariaLuisaCroci** [comment] 2022-10-25 15:54
> @MariaLuisaCroci I just see this is a duplicate of #2833 and can be fixed if you install with `pip install git+https://github.com/flairNLP/flair`. Then it should also work with Python 3.10.
> 
> We will release a new Flair version soon so it will work out of the box again.

that works great! Thanks! :)

**Comment by OleksandrKorovii** [comment] 2022-11-14 09:53
@alanakbik Hi, I'm  interesting, when we can wait, a new version ?

**Closed** 2023-04-02 16:53 UTC
Labels: bug, wontfix
