### ISSUE TITLE
[Bug]: GPT2 finetune error

### ISSUE THREAD

**Issue by shrimonmuke0202** [flairNLP/flair#3160] opened 2023-03-23 08:10 UTC
### Describe the bug

When I trying to fine tune GPT2-medium on our NER task, I got an error "ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`."

### To Reproduce

```python
import flair
from flair import set_seed
from flair.embeddings import TransformerWordEmbeddings
from flair.models import SequenceTagger
from flair.trainers import ModelTrainer
from flair.datasets import ColumnCorpus

Please load any train.txt, dev.txt, test.txt in CoNLL

columns = {0: 'text', 1: 'ner'}


corpus: Corpus = ColumnCorpus(./, columns,
                              train_file=train.txt,
                              test_file=test.txt,
                              dev_file=dev
                              )
    
    logger.info(corpus)
    
    tag_type: str = "ner"
    
    label_dict = corpus.make_label_dictionary(label_type=tag_type)
    logger.info(label_dict)

embeddings = TransformerWordEmbeddings(
        gpt2-medium,
        layers=-1,
        subtoken_pooling=first_last,
        fine_tune=True,
        allow_long_sentences=True,
        use_context=True,
        respect_document_boundaries=flert_args.respect_document_boundaries,
    )
    
    tagger = SequenceTagger(
        hidden_size=256,
        embeddings=embeddings,
        tag_dictionary=label_dict,
        tag_type=tag_type,
        use_crf=model_args.use_crf,
        use_rnn=True,
        rnn_layers=2,
        bidirectional=True,
        allow_unk_predictions=False,
        reproject_embeddings=True,
    )
    
    trainer = ModelTrainer(tagger, corpus)
    
    trainer.fine_tune(
        model,
        learning_rate=0.0005,
        mini_batch_size=8,
        mini_batch_chunk_size=training_args.mini_batch_chunk_size,
        max_epochs=10,
        embeddings_storage_mode=training_args.embeddings_storage_mode,
        param_selection_mode=False,
        use_final_model_for_eval=False,
        save_final_model=False,
        checkpoint=False
    )
```

### Expected behaivor

If the error is solved then the training will start.

2023-03-23 07:05:20,876 epoch 1 - iter 511/5117 - loss 2.30516337 - time (sec): 232.76 - samples/sec: 446.66 - lr: 0.000005
2023-03-23 07:09:10,437 epoch 1 - iter 1022/5117 - loss 1.86657456 - time (sec): 462.32 - samples/sec: 443.36 - lr: 0.000010

### Logs and Stack traces

```stacktrace
Traceback (most recent call last):
  File "/notebooks/cocharne/Blink/train.py", line 147, in <module>
    main()
  File "/notebooks/cocharne/Blink/train.py", line 133, in main
    trainer.fine_tune(
  File "/usr/local/lib/python3.9/dist-packages/flair/trainers/trainer.py", line 971, in fine_tune
    return self.train(
  File "/usr/local/lib/python3.9/dist-packages/flair/trainers/trainer.py", line 541, in train
    loss, datapoint_count = self.model.forward_loss(batch_step)
  File "/usr/local/lib/python3.9/dist-packages/flair/models/sequence_tagger_model.py", line 274, in forward_loss
    sentence_tensor, lengths = self._prepare_tensors(sentences)
  File "/usr/local/lib/python3.9/dist-packages/flair/models/sequence_tagger_model.py", line 287, in _prepare_tensors
    self.embeddings.embed(sentences)
  File "/usr/local/lib/python3.9/dist-packages/flair/embeddings/base.py", line 49, in embed
    self._add_embeddings_internal(data_points)
  File "/usr/local/lib/python3.9/dist-packages/flair/embeddings/transformer.py", line 653, in _add_embeddings_internal
    tensors = self.prepare_tensors(sentences, device=self.force_device)
  File "/usr/local/lib/python3.9/dist-packages/flair/embeddings/transformer.py", line 467, in prepare_tensors
    return self.__build_transformer_model_inputs(sentences, offsets, lengths, flair_tokens, device)
  File "/usr/local/lib/python3.9/dist-packages/flair/embeddings/transformer.py", line 483, in __build_transformer_model_inputs
    batch_encoding = self.tokenizer(
  File "/usr/local/lib/python3.9/dist-packages/transformers/tokenization_utils_base.py", line 2530, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/transformers/tokenization_utils_base.py", line 2616, in _call_one
    return self.batch_encode_plus(
  File "/usr/local/lib/python3.9/dist-packages/transformers/tokenization_utils_base.py", line 2798, in batch_encode_plus
    padding_strategy, truncation_strategy, max_length, kwargs = self._get_padding_truncation_strategies(
  File "/usr/local/lib/python3.9/dist-packages/transformers/tokenization_utils_base.py", line 2435, in _get_padding_truncation_strategies
    raise ValueError(
ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`.
```

##### Flair
0.12.1
##### Pytorch
1.12.1+cu116
##### Transformers
4.27.0
#### GPU
True

**Comment by helpmefindaname** [comment] 2023-03-23 08:40
Hi @shrimonmuke0202 
this is a duplicate of https://github.com/flairNLP/flair/issues/3050 you will find the solution there.

**Closed by helpmefindaname** 2023-03-23 08:40 UTC
Labels: bug
