### ISSUE TITLE
Windows : cannot instantiate 'PosixPath' on your system

### ISSUE THREAD

**Issue by RansSelected** [flairNLP/flair#2623] opened 2022-02-07 13:45 UTC
**Describe the bug**
cannot instantiate 'PosixPath' on Windows

**To Reproduce**
Steps to reproduce the behavior :
Run the code:

`
from flair.data import Sentence
from flair.models import SequenceTagger

sentence = Sentence('Machine learning is a field of AI')

model = SequenceTagger.load('frame')

model.predict(sentence)
`

**Expected behavior**
Expected to download and load SRL(frame) model

**Screenshots**
![image](https://user-images.githubusercontent.com/43318715/152799342-b158a238-a211-4553-8f5e-536781c2c43b.png)

**Environment (please complete the following information):**
 - OS Windows 10:
 - Version [e.g. flair-0.10, python 3.7.11]:

**Additional context**

**Comment by whoisjones** [comment] 2022-02-07 20:38
Duplicate of gh-1052.

**Comment by helpmefindaname** [comment] 2022-02-08 18:52
this is an issue that pickle has with pathlib, you can use this solution: https://stackoverflow.com/a/68796747

**Closed** 2022-06-29 12:32 UTC
Labels: bug, wontfix
