### ISSUE TITLE
How to tag your own corpus to train a NER model

### ISSUE THREAD

**Issue by fmafelipe** [flairNLP/flair#2749] opened 2022-05-04 03:32 UTC
I want to train a NER model with my own corpus, however, when I label each token as shown in the example in tutorial 6 (seen below) in the "Reading Your Own Sequence Labeling Dataset" section it doesn't work.

George N B-PER
Washington N I-PER
went V O
to P O
Washington N B-LOC

Sam N B-PER
Houston N I-PER
stayed V O
home N O

Clearly I'm only interested in the NER label column. I have seen that with the flair update, the NER models no longer show the tags as <B-PER> but only <PER> for example.
Is there a new way to tag a sequence for a NER model in a corpus?
What is the correct way?

(Excuse my English, I'm from LATAM)

**Comment by bogdankjastrzebski** [comment] 2022-05-06 00:01
Hi!

I'm not sure, what the problem might be. The tutorial shows the correct way to load the corpus, though the output format changed. I've tested it with flair v0.11.1 in [this](https://colab.research.google.com/drive/17xLnsyIddGzUByb23fWS7mu1STT_mt-h?usp=sharing) Colab notebook, and it looks fine. As I understand (correct me if I'm wrong), your corpus has only the NER label column. In the notebook, I added a modified version of the tutorial with NER label only.

Without additional information, unfortunately, I don't know what the problem is. If you could explain, what exactly went wrong, I'm here to help.

**Comment by fmafelipe** [comment] 2022-05-06 17:58
Hello, thank you very much, I think the problem was my fault, because I was not labeling all the tokens with the prefix B or I, for example I was labeling some names with "B-PER" and another only with "PER".
Now if you can help me with the understanding of those "prefixes" B, I, E, S. 
I don't understand on what occasions each one is used.

**Comment by dobbersc** [comment] 2022-05-07 19:47
Hey @fmafelipe,

The prefixes you are describing are part of an annotation convention. E.g. the BIO or BIOES scheme. The purpose of these annotation prefixes is to annotate spans in a sentence, i.e. a continuous sequence of tokens in the sentence, on token level. 

Here is a table of what the prefixes actually mean (replace PER with any other annotation):
| Annotation | Explanation                                                     |
|------------|-----------------------------------------------------------------|
| B-PER      | *beginning* token of a PER span                                 |
| I-PER      | *inside* token of a PER span                                    |
| O          | *outside* token (the token is not part of any named entity span) |
| E-PER      | *ending* token of a PER span (specific to the BIOES scheme)                                |
| S-PER      | *single* token of a PER span (specific to the BIOES scheme)                                   |


Example: Take the sentence "George Washington was born in Washington, United States of America".

The sentence annotated in BIO format: "George (B-PER) Washington (I-PER) was (O) born (O) in (O) Washington (B-LOC) , (O) United (B-LOC) States (I-LOC) of (I-LOC) America (I-LOC)".

The sentence annotated in BIOES format: "George (B-PER) Washington (E-PER) was (O) born (O) in (O) Washington (S-LOC) , (O) United (B-LOC) States (I-LOC) of (I-LOC) America (E-LOC)".

**Comment by alanakbik** [comment] 2022-05-09 03:05
Closing since question is answered (thanks @dobbersc), but feel free to reopen if there are more questions!

**Closed by alanakbik** 2022-05-09 03:05 UTC
Labels: question

**Comment by fmafelipe** [comment] 2022-05-09 03:20
Thank you very much @dobbersc 
The explanation was very helpful.
