### ISSUE TITLE
[Bug]: No such file or directory: conll_03

### ISSUE THREAD

**Issue by AugustasMacys** [flairNLP/flair#3120] opened 2023-02-20 16:56 UTC
### Describe the bug

Seems that I cannot download dataset while following tutorial 13

### To Reproduce

```python
from flair.datasets import CONLL_03
CONLL_03()
```

### Expected behaivor

Dataset is downloaded

### Logs and Stack traces

```stacktrace
2023-02-20 16:49:06,547 ----------------------------------------------------------------------------------------------------
2023-02-20 16:49:06,551 WARNING: CoNLL-03 dataset not found at "/Users/augustas/.flair/datasets/conll_03".
2023-02-20 16:49:06,552 Instructions for obtaining the data can be found here: https://www.clips.uantwerpen.be/conll2003/ner/"
2023-02-20 16:49:06,553 ----------------------------------------------------------------------------------------------------
```

### Environment

python 3.7.11

**Comment by helpmefindaname** [comment] 2023-02-20 22:22
Hi @AugustasMacys 
like the logs are telling you, you need to obtain the dataset and put it into the right place yourself. 
There is currently an open PR to make this automatically https://github.com/flairNLP/flair/pull/3105, but as long as that PR is not merged, you are getting exactly the intended behavior.

**Closed by helpmefindaname** 2023-02-20 22:22 UTC
Labels: bug
