### ISSUE TITLE
[Bug]:  TransformerWordEmbeddings & use_context=True produce random embeddings

### ISSUE THREAD

**Issue by marc-r-vincent** [flairNLP/flair#3335] opened 2023-10-11 15:45 UTC
### Describe the bug

When instantiating a TransformerWordEmbeddings object with setting use_context=True as the only non default option (other than the model) and applying to the same input string, the result changes.

Also, the output embedding is not the same as with previous flair version.

### To Reproduce

```python
from flair.data import Sentence
from flair.embeddings import TransformerWordEmbeddings

phrase_0 = Sentence("a  uui")
embeddings_a = TransformerWordEmbeddings(
    'roberta-base',
    use_context=True
)
ebd_a = embeddings_a.embed(phrase_0)

phrase_1 = Sentence("a  uui")
embeddings_b = TransformerWordEmbeddings(
    'roberta-base',
    use_context=True
)
ebd_b = embeddings_b.embed(phrase_1)

print(
    "token run 0:", ebd_a[-1][-1], "\n",
    "embedding end run 0:", ebd_a[-1][-1].embedding.tolist()[-2:], "\n",
    "token run 1: ", ebd_b[-1][-1], "\n",
    "embedding end run 1:", ebd_b[-1][-1].embedding.tolist()[-2:]
)
```
Output gives me:

token run 0: Token[1]: "uui"
embedding end run 0: [-0.14627917110919952, 0.05319966748356819]
token run 1:  Token[1]: "uui"
embedding end run 1: [-0.1271992027759552, 0.1670898050069809]

### Expected behavior

"embedding end run 0" and "embedding end run 1" should be identical

##### Flair
0.12.2
##### Pytorch
1.13.1+cu117
##### Transformers
4.30.2
#### GPU
True

**Comment by helpmefindaname** [comment] 2023-10-11 19:23
hi @marc-r-vincent 
this is because the default for `use_context_separator` is true. A new special token will be added to the vocabulary and initialized randomly. If you pass `use_context_separator=False`, you should have reproducible embeddings.

**Comment by marc-r-vincent** [comment] 2023-10-11 20:03
Hi Benedikt @helpmefindaname , thank you for your answer,  when I use use_context_separator=False and use_context=True, I do indeed get reproducible embeddings but I also effectively get the same result than when using use_context=False, i.e. the context does not seem to be used at all.

It seems to differ from the behavior of a previous version of flair (0.8.0.post1) where setting use_context=True (no use_context_separator option), did allow for reproducible embeddings that were also different than the embeddings computed with use_context=False.

**Comment by helpmefindaname** [comment] 2023-10-13 09:24
Hi @marc-r-vincent 
you get the same as `use_context=False`, because there is no context set in your sentences.

If you would call:
```
paragraph = [
    Sentence("this is the first sentence."),
    Sentence("this is the second sentence."),
]

contextual_embedding.embed(paragraph)
```

you would get different results than calling:
```
paragraph = [
    Sentence("this is the first sentence."),
    Sentence("this is the second sentence."),
]

contextual_embedding.embed(paragraph[0])
contextual_embedding.embed(paragraph[1])
```

As in the first example, the sentences are set as context for each other, while on the second they are independent.

**Comment by alanakbik** [comment] 2023-10-24 14:34
Closing, since question is answered, but feel free to reopen if there are further questions!

**Closed by alanakbik** 2023-10-24 14:34 UTC
Labels: bug
