### ISSUE TITLE
flair ner  import failing on mac ubuntu and google colab

### ISSUE THREAD

**Issue by ajaypr55** [flairNLP/flair#1833] opened 2020-08-29 04:04 UTC
i have been using flair for long but last two days . updated flair to new version
<img width="1228" alt="Screenshot 2020-08-29 at 9 33 39 AM" src="https://user-images.githubusercontent.com/12379507/91628156-bfe7c000-e9da-11ea-9289-fb7e3421108b.png">

# load the NER tagger
tagger = SequenceTagger.load('ner')

this fails with OSError: HEAD request failed for url https://s3.eu-central-1.amazonaws.com/alan-nlp/resources/models-v0.4/NER-conll03-english/en-ner-conll03-v0.4.pt with status code 301. tried everything possibly on ubuntu,mac , remote , clean install . nothing working .

**Comment by asm-cygu** [comment] 2020-08-29 07:57
In progress I hope :-)

https://github.com/flairNLP/flair/issues/1831

**Comment by alanakbik** [comment] 2020-08-29 08:03
yes getting there :) closing since duplicate of #1831

**Closed by alanakbik** 2020-08-29 08:03 UTC
Labels: question
