### ISSUE TITLE
Failing to install Flair on Apple Silicon

### ISSUE THREAD

**Issue by mishraaditya595** [flairNLP/flair#2853] opened 2022-07-05 08:43 UTC
**Describe the bug**
I am trying to install flair on my MacBook m1 air. I have used both `pip install flair` and `pip3 install flair but it fails everytime.

Here are the terminal logs:
`DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting flair
  Using cached flair-0.11.3-py3-none-any.whl (401 kB)
Collecting sqlitedict>=1.6.0
  Using cached sqlitedict-2.0.0-py3-none-any.whl
Collecting langdetect
  Using cached langdetect-1.0.9-py3-none-any.whl
Collecting gensim>=3.4.0
  Using cached gensim-4.2.0-cp39-cp39-macosx_11_0_arm64.whl
Collecting bpemb>=0.3.2
  Using cached bpemb-0.3.3-py3-none-any.whl (19 kB)
Collecting segtok>=1.5.7
  Using cached segtok-1.5.11-py3-none-any.whl (24 kB)
Collecting scikit-learn>=0.21.3
  Using cached scikit_learn-1.1.1-cp39-cp39-macosx_11_0_arm64.whl
Collecting pptree
  Using cached pptree-3.1-py3-none-any.whl
Collecting more-itertools
  Using cached more_itertools-8.13.0-py3-none-any.whl (51 kB)
Collecting lxml
  Using cached lxml-4.9.1-cp39-cp39-macosx_11_0_arm64.whl
Collecting mpld3==0.3
  Using cached mpld3-0.3-py3-none-any.whl
Collecting tabulate
  Using cached tabulate-0.8.10-py3-none-any.whl (29 kB)
Requirement already satisfied: matplotlib>=2.2.3 in /opt/homebrew/lib/python3.9/site-packages (from flair) (3.5.2)
Requirement already satisfied: tqdm>=4.26.0 in /opt/homebrew/lib/python3.9/site-packages (from flair) (4.64.0)
Collecting janome
  Using cached Janome-0.4.2-py2.py3-none-any.whl (19.7 MB)
Requirement already satisfied: regex in /opt/homebrew/lib/python3.9/site-packages (from flair) (2022.6.2)
Requirement already satisfied: deprecated>=1.2.4 in /opt/homebrew/lib/python3.9/site-packages (from flair) (1.2.13)
Collecting konoha<5.0.0,>=4.0.0
  Using cached konoha-4.6.5-py3-none-any.whl (20 kB)
Collecting ftfy
  Using cached ftfy-6.1.1-py3-none-any.whl (53 kB)
Collecting gdown==4.4.0
  Using cached gdown-4.4.0-py3-none-any.whl
Requirement already satisfied: python-dateutil>=2.6.1 in /opt/homebrew/lib/python3.9/site-packages (from flair) (2.8.2)
Collecting wikipedia-api
  Using cached Wikipedia_API-0.5.4-py3-none-any.whl
Collecting hyperopt>=0.2.7
  Using cached hyperopt-0.2.7-py2.py3-none-any.whl (1.6 MB)
Collecting conllu>=4.0
  Using cached conllu-4.4.2-py2.py3-none-any.whl (15 kB)
Collecting huggingface-hub
  Using cached huggingface_hub-0.8.1-py3-none-any.whl (101 kB)
Collecting transformers>=4.0.0
  Using cached transformers-4.20.1-py3-none-any.whl (4.4 MB)
Collecting torch!=1.8,>=1.5.0
  Using cached torch-1.12.0-cp39-none-macosx_11_0_arm64.whl (48.9 MB)
Collecting sentencepiece==0.1.95
  Using cached sentencepiece-0.1.95-cp39-cp39-macosx_11_0_arm64.whl
Requirement already satisfied: requests[socks] in /opt/homebrew/lib/python3.9/site-packages (from gdown==4.4.0->flair) (2.28.1)
Requirement already satisfied: six in /opt/homebrew/lib/python3.9/site-packages (from gdown==4.4.0->flair) (1.16.0)
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.11.1-py3-none-any.whl (128 kB)
Collecting filelock
  Using cached filelock-3.7.1-py3-none-any.whl (10 kB)
Requirement already satisfied: numpy in /opt/homebrew/lib/python3.9/site-packages (from bpemb>=0.3.2->flair) (1.23.0)
Requirement already satisfied: wrapt<2,>=1.10 in /opt/homebrew/lib/python3.9/site-packages (from deprecated>=1.2.4->flair) (1.14.1)
Collecting smart-open>=1.8.1
  Using cached smart_open-6.0.0-py3-none-any.whl (58 kB)
Requirement already satisfied: scipy>=0.18.1 in /opt/homebrew/lib/python3.9/site-packages (from gensim>=3.4.0->flair) (1.8.1)
Collecting future
  Using cached future-0.18.2-py3-none-any.whl
Collecting cloudpickle
  Using cached cloudpickle-2.1.0-py3-none-any.whl (25 kB)
Collecting networkx>=2.2
  Using cached networkx-2.8.4-py3-none-any.whl (2.0 MB)
Collecting py4j
  Using cached py4j-0.10.9.5-py2.py3-none-any.whl (199 kB)
Collecting overrides<4.0.0,>=3.0.0
  Using cached overrides-3.1.0-py3-none-any.whl
Collecting importlib-metadata<4.0.0,>=3.7.0
  Using cached importlib_metadata-3.10.1-py3-none-any.whl (14 kB)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/homebrew/lib/python3.9/site-packages (from matplotlib>=2.2.3->flair) (1.4.3)
Requirement already satisfied: cycler>=0.10 in /opt/homebrew/lib/python3.9/site-packages (from matplotlib>=2.2.3->flair) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/homebrew/lib/python3.9/site-packages (from matplotlib>=2.2.3->flair) (4.33.3)
Requirement already satisfied: pillow>=6.2.0 in /opt/homebrew/lib/python3.9/site-packages (from matplotlib>=2.2.3->flair) (9.2.0)
Requirement already satisfied: pyparsing>=2.2.1 in /opt/homebrew/lib/python3.9/site-packages (from matplotlib>=2.2.3->flair) (3.0.9)
Requirement already satisfied: packaging>=20.0 in /opt/homebrew/lib/python3.9/site-packages (from matplotlib>=2.2.3->flair) (21.3)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Requirement already satisfied: joblib>=1.0.0 in /opt/homebrew/lib/python3.9/site-packages (from scikit-learn>=0.21.3->flair) (1.1.0)
Collecting typing-extensions
  Using cached typing_extensions-4.3.0-py3-none-any.whl (25 kB)
Collecting pyyaml>=5.1
  Using cached PyYAML-6.0-cp39-cp39-macosx_11_0_arm64.whl (173 kB)
Collecting tokenizers!=0.11.3,<0.13,>=0.11.1
  Using cached tokenizers-0.12.1.tar.gz (220 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting wcwidth>=0.2.5
  Using cached wcwidth-0.2.5-py2.py3-none-any.whl (30 kB)
Collecting zipp>=0.5
  Using cached zipp-3.8.0-py3-none-any.whl (5.4 kB)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/lib/python3.9/site-packages (from requests[socks]->gdown==4.4.0->flair) (2022.6.15)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/lib/python3.9/site-packages (from requests[socks]->gdown==4.4.0->flair) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/homebrew/lib/python3.9/site-packages (from requests[socks]->gdown==4.4.0->flair) (1.26.9)
Requirement already satisfied: charset-normalizer<3,>=2 in /opt/homebrew/lib/python3.9/site-packages (from requests[socks]->gdown==4.4.0->flair) (2.1.0)
Collecting soupsieve>1.2
  Using cached soupsieve-2.3.2.post1-py3-none-any.whl (37 kB)
Collecting PySocks!=1.5.7,>=1.5.6
  Using cached PySocks-1.7.1-py3-none-any.whl (16 kB)
Building wheels for collected packages: tokenizers
  Building wheel for tokenizers (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for tokenizers (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-11-arm64-cpython-39
      creating build/lib.macosx-11-arm64-cpython-39/tokenizers
      copying py_src/tokenizers/__init__.py -> build/lib.macosx-11-arm64-cpython-39/tokenizers
      creating build/lib.macosx-11-arm64-cpython-39/tokenizers/models
      copying py_src/tokenizers/models/__init__.py -> build/lib.macosx-11-arm64-cpython-39/tokenizers/models
      creating build/lib.macosx-11-arm64-cpython-39/tokenizers/decoders
      copying py_src/tokenizers/decoders/__init__.py -> build/lib.macosx-11-arm64-cpython-39/tokenizers/decoders
      creating build/lib.macosx-11-arm64-cpython-39/tokenizers/normalizers
      copying py_src/tokenizers/normalizers/__init__.py -> build/lib.macosx-11-arm64-cpython-39/tokenizers/normalizers
      creating build/lib.macosx-11-arm64-cpython-39/tokenizers/pre_tokenizers
      copying py_src/tokenizers/pre_tokenizers/__init__.py -> build/lib.macosx-11-arm64-cpython-39/tokenizers/pre_tokenizers
      creating build/lib.macosx-11-arm64-cpython-39/tokenizers/processors
      copying py_src/tokenizers/processors/__init__.py -> build/lib.macosx-11-arm64-cpython-39/tokenizers/processors
      creating build/lib.macosx-11-arm64-cpython-39/tokenizers/trainers
      copying py_src/tokenizers/trainers/__init__.py -> build/lib.macosx-11-arm64-cpython-39/tokenizers/trainers
      creating build/lib.macosx-11-arm64-cpython-39/tokenizers/implementations
      copying py_src/tokenizers/implementations/byte_level_bpe.py -> build/lib.macosx-11-arm64-cpython-39/tokenizers/implementations
      copying py_src/tokenizers/implementations/sentencepiece_unigram.py -> build/lib.macosx-11-arm64-cpython-39/tokenizers/implementations
      copying py_src/tokenizers/implementations/sentencepiece_bpe.py -> build/lib.macosx-11-arm64-cpython-39/tokenizers/implementations
      copying py_src/tokenizers/implementations/base_tokenizer.py -> build/lib.macosx-11-arm64-cpython-39/tokenizers/implementations
      copying py_src/tokenizers/implementations/__init__.py -> build/lib.macosx-11-arm64-cpython-39/tokenizers/implementations
      copying py_src/tokenizers/implementations/char_level_bpe.py -> build/lib.macosx-11-arm64-cpython-39/tokenizers/implementations
      copying py_src/tokenizers/implementations/bert_wordpiece.py -> build/lib.macosx-11-arm64-cpython-39/tokenizers/implementations
      creating build/lib.macosx-11-arm64-cpython-39/tokenizers/tools
      copying py_src/tokenizers/tools/__init__.py -> build/lib.macosx-11-arm64-cpython-39/tokenizers/tools
      copying py_src/tokenizers/tools/visualizer.py -> build/lib.macosx-11-arm64-cpython-39/tokenizers/tools
      copying py_src/tokenizers/__init__.pyi -> build/lib.macosx-11-arm64-cpython-39/tokenizers
      copying py_src/tokenizers/models/__init__.pyi -> build/lib.macosx-11-arm64-cpython-39/tokenizers/models
      copying py_src/tokenizers/decoders/__init__.pyi -> build/lib.macosx-11-arm64-cpython-39/tokenizers/decoders
      copying py_src/tokenizers/normalizers/__init__.pyi -> build/lib.macosx-11-arm64-cpython-39/tokenizers/normalizers
      copying py_src/tokenizers/pre_tokenizers/__init__.pyi -> build/lib.macosx-11-arm64-cpython-39/tokenizers/pre_tokenizers
      copying py_src/tokenizers/processors/__init__.pyi -> build/lib.macosx-11-arm64-cpython-39/tokenizers/processors
      copying py_src/tokenizers/trainers/__init__.pyi -> build/lib.macosx-11-arm64-cpython-39/tokenizers/trainers
      copying py_src/tokenizers/tools/visualizer-styles.css -> build/lib.macosx-11-arm64-cpython-39/tokenizers/tools
      running build_ext
      running build_rust
      error: can't find Rust compiler
      
      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.
      
      To update pip, run:
      
          pip install --upgrade pip
      
      and then retry package installation.
      
      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tokenizers
Failed to build tokenizers`

**Environment:**
 - OS [e.g. iOS, Linux]: MacOS Monterey
 - Version [e.g. flair-0.3.2]: 0.11.3

**Additional context**
I tried it on my Linux PC and it's working fine. I think it is a mac specific issue.

**Comment by helpmefindaname** [comment] 2022-07-05 23:05
Hi @mishraaditya595 
this looks like it is failing to install the tokenizers dependency, I suppose the contributors and maintainers of that repository will be able to help you with that problem (or work on a fix)

**Comment by Akshaysehgal2005** [comment] 2022-09-07 20:49
Still facing this bug. flair-0.11.3

**Comment by rupalandge** [comment] 2022-11-08 07:28
I am also unable to install flair on mac M1 pro.
pip install flair

**Comment by dalmad2** [comment] 2022-11-22 19:32
Is there any update? I am having the same issue.

**Comment by helpmefindaname** [comment] 2022-11-23 19:14
@dalmad2 
> this looks like it is failing to install the tokenizers dependency, I suppose the contributors and maintainers of that repository will be able to help you with that problem (or work on a fix)

I am not sure what kind of update is expected. I suppose either going to the other repo or providing more information why you think this should not be a tokenizers problem would be helpful.

**Comment by dalmad2** [comment] 2022-11-23 19:20
@helpmefindaname Actually, my co-worker has experienced a similar issue. I can't provide more information.
I hope you could close this ticket so that others would expect no update for this issue.

**Comment by FedericoCampe8** [comment] 2022-12-30 14:13
Same here but for sentencepiece
```
      Failed to find sentencepiece pkg-config
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> sentencepiece
```

**Comment by peterth3** [comment] 2023-02-12 18:45
I'm on an M1 Mac running Ventura 13.1. Installing via `pip install flair` doesn't work but via `git+` does work for me.

```sh
pip install git+https://github.com/flairNLP/flair.git
```

I think the issue is with the last 0.11.3 release. https://github.com/flairNLP/flair/blob/d20c3fd07474e6103780fbe2b65302871f8db33d/requirements.txt#L19

vs. the latest commit.
https://github.com/flairNLP/flair/blob/38b8cf5fd93d4a624a66141e2eaebc02302944e5/requirements.txt#L13

Maybe this will be fixed in the next release?

**Closed** 2023-05-05 12:19 UTC
Labels: bug
