### ISSUE TITLE
PyPI flair install failing

### ISSUE THREAD

**Issue by mdrmuhaimin** [flairNLP/flair#1327] opened 2019-12-24 04:14 UTC
**Description**
PyPI flair install is failing. When we try to install `pip install flair` it failed with an error message 
```
ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI.
tiny-tokenizer depends on SudachiDict_core@ https://object-storage.tyo2.conoha.io/v1/nc_2520839e1f9641b08211a5c85243124a/sudachi/SudachiDict_core-20190927.tar.gz 
```

**To Reproduce**
Temporary workaround
Install tiny-tokenizer manually before installing flair
`pip install tiny-tokenizer flair`

**Comment by dhruvrnaik** [comment] 2019-12-24 14:12
Yes, faced the same problem yesterday on Google Colab.
Installing tiny-tokenizer before flair works.

**Comment by IS5882** [comment] 2019-12-25 19:00
Same here I hope it get fixed soon

**Comment by jainal09** [comment] 2019-12-27 07:27
I tried 

`pip install tiny-tokenizer`

`pip install flair`

and it fixed the issue 

Now when I try 

```
from flair.models import TextClassifier
from flair.data import Sentence
classifier = TextClassifier.load('en-sentiment')
```
This is the Output

> 2019-12-27 07:22:54,083 loading file /root/.flair/models/imdb-v0.4.pt

**Comment by IslamAlam** [comment] 2020-01-01 12:53
I had the same issue too

**Comment by alanakbik** [comment] 2020-01-07 15:39
We've removed a lot of dependencies from master to fix the install. Will be fixed with next version release of Flair. In the meantime, you can install like this to get the latest version without the tiny_tokenizer error: 

```console
pip install --upgrade git+https://github.com/zalandoresearch/flair.git
```

**Comment by alanakbik** [comment] 2020-01-24 17:23
We released a new version of flair just now that fixes this.

**Closed by alanakbik** 2020-01-24 17:23 UTC
Labels: bug

**Comment by azharmajeed** [comment] 2020-04-07 13:12
Hi I am trying to install flair using pip install flair but i get this error:-
ERROR: Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Max retries exceeded with url: /packages/03/29/81e3c9a829ec50857c23d82560941625f6b42ce76ee7c56ea9529e959d18/flair-0.4.5-py3-none-any.whl (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))

I get a similar error even if i try pip install tiny-tokenizer. 
I ran (pip install --upgrade pip --trusted-host pypi.org --trusted-host files.pythonhosted.org) and then tried to install the above packages but still no luck. 

Alternatively I tried conda install -c bioconda flair but that throws an error something like this-
Package pysam conflicts for:
flair -> pysam
Package numpy conflicts for:
flair -> numpy
Package rpy2 conflicts for:
flair -> rpy2
Package tqdm conflicts for:
flair -> tqdm
Package r-ggplot2 conflicts for:
flair -> r-ggplot2=2.2.1
(lot of other packages it conflicts with)

I tried installing in a new environment but the same issue persists. Is there any other way to install the package?
Would really appreciate if anyone could help me out with this.
