### ISSUE TITLE
Wrong condition for training without dev in ModelTrainer

### ISSUE THREAD

**Issue by Kruszylo** [flairNLP/flair#1584] opened 2020-05-06 14:17 UTC
https://github.com/flairNLP/flair/blob/856c0a3e71bb68545ca841fd3d74b45b7315d926/flair/trainers/trainer.py#L188

Is this correct? I don't want to pass `dev` subset, I just want to train tagger.

**Comment by djstrong** [comment] 2020-05-06 14:55
It is correct. I am not sure if dev can be empty, but if not then put there e.g. one example from train.

**Comment by alanakbik** [comment] 2020-05-06 17:39
Current this works, because a dev set is always automatically sampled from train even if you don't provide one. But if you set `train_with_dev=True`, this dev set is merged back into train. Then you only have train and test data, but no dev.

**Comment by allenciox** [comment] 2020-05-14 19:30
So, Flair doesn't appear to work at all if you don't supply a dev set as input to ColumnCorpus class.   The issue is that in that case, it calls the superclass _init with a subset of the training data as dev.  The super class generates the sample, but it returns a torch.datasubset class instead of a ColumnDataset class, which doesn't work when it is passed into SequenceTagger constructor.

**Comment by alanakbik** [comment] 2020-05-14 20:04
Could you clarify? I removed the dev set from one of my datasets and it still worked: 

```console
2020-05-14 22:02:37,705 Reading data from resources/tasks/penn_nodev
2020-05-14 22:02:37,705 Train: resources/tasks/penn_nodev/train.conll
2020-05-14 22:02:37,705 Dev: None
2020-05-14 22:02:37,705 Test: resources/tasks/penn_nodev/test.conll
  0%|          | 0/30074 [00:00<?, ?it/s]2020-05-14 22:02:45,725 Computing label dictionary. Progress:
100%|██████████| 30074/30074 [00:00<00:00, 49795.06it/s]
2020-05-14 22:02:46,329 [b'ADP', b'NOUN', b'DET', b'PUNCT', b'PROPN', b'AUX', b'VERB', b'SYM', b'NUM', b'CCONJ', b'PRON', b'ADV', b'ADJ', b'PART', b'X', b'INTJ']
Corpus: 26015 train + 2890 dev + 4059 test sentences
2020-05-14 22:02:48,406 ----------------------------------------------------------------------------------------------------
2020-05-14 22:02:48,406 Model: "SequenceTagger(
  (embeddings): BytePairEmbeddings(model=bpe-en-100000-50)
  (word_dropout): WordDropout(p=0.05)
  (locked_dropout): LockedDropout(p=0.5)
  (embedding2nn): Linear(in_features=100, out_features=100, bias=True)
  (linear): Linear(in_features=100, out_features=16, bias=True)
  (beta): 1.0
  (weights): None
  (weight_tensor) None
)"
2020-05-14 22:02:48,406 ----------------------------------------------------------------------------------------------------
2020-05-14 22:02:48,406 Corpus: "Corpus: 26015 train + 2890 dev + 4059 test sentences"
2020-05-14 22:02:48,407 ----------------------------------------------------------------------------------------------------
2020-05-14 22:02:48,407 Parameters:
2020-05-14 22:02:48,407  - learning_rate: "3e-05"
2020-05-14 22:02:48,407  - mini_batch_size: "16"
2020-05-14 22:02:48,407  - patience: "3"
2020-05-14 22:02:48,407  - anneal_factor: "0.5"
2020-05-14 22:02:48,407  - max_epochs: "4"
2020-05-14 22:02:48,407  - shuffle: "True"
2020-05-14 22:02:48,407  - train_with_dev: "False"
2020-05-14 22:02:48,407  - batch_growth_annealing: "False"
2020-05-14 22:02:48,407 ----------------------------------------------------------------------------------------------------
2020-05-14 22:02:48,407 Model training base path: "resources/taggers/test_predict"
2020-05-14 22:02:48,407 ----------------------------------------------------------------------------------------------------
2020-05-14 22:02:48,407 Device: cuda:0
2020-05-14 22:02:48,407 ----------------------------------------------------------------------------------------------------
2020-05-14 22:02:48,407 Embeddings storage mode: gpu
2020-05-14 22:02:48,407 ----------------------------------------------------------------------------------------------------
2020-05-14 22:02:52,642 epoch 1 - iter 162/1626 - loss 2.72933916 - samples/sec: 612.88
2020-05-14 22:02:57,054 epoch 1 - iter 324/1626 - loss 2.63959199 - samples/sec: 588.36
```

**Comment by allenciox** [comment] 2020-05-14 20:14
So, just to note, I am using Flair 0.4.5, which is dated 3/4/2020, which is the version that gets downloaded when I do a pip install flair –upgrade

So here is what I do:

import py_ner, imp
import pprint
pp=pprint.PrettyPrinter(indent=4)
%env FLAIR_CACHE_ROOT=/bigdisk/lax/cox/.flair
%env CUDA_VISIBLE_DEVICES=1,2
from pathlib import Path
import flair
# column format
columns = {0: "text", 1: "pos", 2: "entity"}

# Identify data location
base_path = Path(flair.cache_root) / "datasets"
data_folder = base_path / "wnut17_converted"

# ColumnCorpus:
corpus= py_ner.build_flair_corpus(data_folder, columns,
                                        train_file="wnut17.train",
                                        # dev_file="emerging.dev.corpusTokens.stdTag.txt",
                                        test_file="emerging.test.corpusTokens.stdTag.txt"
                                        )
pp.pprint(corpus)

print(corpus.train)
print(corpus.dev)
print(corpus.test)


(inside py_ner if the following function: which, as you see, is a wrapper around calling ColumnCorpus:)
##########################################################
# build_flair_corpus builds a corpus of training, plus optional dev and test splits for evaluation
#########################################################
def build_flair_corpus(
    data_folder: Union[str, Path],
    column_format: Dict[int, str],
    train_file=None,
    test_file=None,
    dev_file=None,
    tag_to_bioes=None,
    comment_symbol: str = None,
    in_memory: bool = True,
    encoding: str = "utf-8",
    document_separator_token: str = None,
    )-> ColumnCorpus :
    """
    Instantiates a Corpus from tab-delimited column-formatted sequence data

    :param data_folder: base folder with the task data
    :param column_format: a map specifying the column format
    :param train_file: the name of the train file
    :param test_file: the name of the test file
    :param dev_file: the name of the dev file, if None, dev data is sampled from train
    :param tag_to_bioes: whether to convert to BIOES tagging scheme
    :param comment_symbol: if set, lines that begin with this symbol are treated as comments
    :param in_memory: If set to True, the dataset is kept in memory as Sentence objects, otherwise does disk reads
    :param document_separator_token: If provided, multiple sentences are read into one object. Provide the string token
    that indicates that a new document begins
    :return: a Corpus with annotated train, dev and test data
    """

    if train_file == None :
        print("No training data specified.")
        return None
    else :
        train_ds=data_folder / train_file
        if not train_ds.is_file():
            print("Training file does not exist.");
            return None

    if dev_file == None :
        print("No dev data specified")
        dev_ds = None
    else :
        dev_ds=data_folder / dev_file
        if not dev_ds.is_file():
            print("Development file does not exist.");
            return None
    if test_file == None :
        print("No test data specified")
        test_ds = None
    else :
        test_ds=data_folder / test_file
        if not test_ds.is_file():
            print("Test file does not exist.");
            return None

    corpus = ColumnCorpus(data_folder,
                        column_format,
                        train_file=train_ds,
                        dev_file=dev_ds,
                        test_file=test_ds,
                        tag_to_bioes=tag_to_bioes,
                        comment_symbol=comment_symbol,
                        in_memory=in_memory,
                        encoding=encoding,
                        document_separator_token=document_separator_token
                        )
    return corpus
  )




Here is the result (from the Jupyter notebook):

nv: FLAIR_CACHE_ROOT=/bigdisk/lax/cox/.flair
env: CUDA_VISIBLE_DEVICES=1,2
No dev data specified
2020-05-14 16:07:43,809 Reading data from /r/ge.unx.sas.com/vol/vol410/u41/cox/.flair/datasets/wnut17_converted
2020-05-14 16:07:43,810 Train: /r/ge.unx.sas.com/vol/vol410/u41/cox/.flair/datasets/wnut17_converted/wnut17.train
2020-05-14 16:07:43,810 Dev: None
2020-05-14 16:07:43,810 Test: /r/ge.unx.sas.com/vol/vol410/u41/cox/.flair/datasets/wnut17_converted/emerging.test.corpusTokens.stdTag.txt
<flair.datasets.ColumnCorpus object at 0x7fa0893a4c90>
<torch.utils.data.dataset.Subset object at 0x7fa0fe80ab50>
<torch.utils.data.dataset.Subset object at 0x7fa0fe80a250>
<flair.datasets.ColumnDataset object at 0x7fa096235ed0>



It appears, whenever it samples the data, it generates the dataset.subset object instead of a ColumnDataset, which causes SequenceTagger to barf.  Now, it might be fixed in a version, I don’t have.


Here is the result when I uncomment the line including the dev file and re-submit

env: FLAIR_CACHE_ROOT=/bigdisk/lax/cox/.flair
env: CUDA_VISIBLE_DEVICES=1,2
2020-05-14 16:13:11,559 Reading data from /r/ge.unx.sas.com/vol/vol410/u41/cox/.flair/datasets/wnut17_converted
2020-05-14 16:13:11,560 Train: /r/ge.unx.sas.com/vol/vol410/u41/cox/.flair/datasets/wnut17_converted/wnut17.train
2020-05-14 16:13:11,560 Dev: /r/ge.unx.sas.com/vol/vol410/u41/cox/.flair/datasets/wnut17_converted/emerging.dev.corpusTokens.stdTag.txt
2020-05-14 16:13:11,560 Test: /r/ge.unx.sas.com/vol/vol410/u41/cox/.flair/datasets/wnut17_converted/emerging.test.corpusTokens.stdTag.txt
<flair.datasets.ColumnCorpus object at 0x7fa09724bf50>
<flair.datasets.ColumnDataset object at 0x7fa35da05050>
<flair.datasets.ColumnDataset object at 0x7fa101f92a90>
<flair.datasets.ColumnDataset object at 0x7fa2e48d8750>




Now they are all ColumnDataset classes and everything goes forward fine.


Jim

**Comment by alanakbik** [comment] 2020-05-14 20:34
Can you also share the code you use for training, i.e. that throws the error?

**Closed** 2020-09-18 21:33 UTC
Labels: wontfix
