### ISSUE TITLE
[Bug]: Cannot use NER models offline

### ISSUE THREAD

**Issue by mirix** [flairNLP/flair#3381] opened 2023-12-01 14:19 UTC
### Describe the bug

I have changed the default cache root. When I am online, the models are downloaded (as long as the folders do not exist already). Then I can go offline and it still works.

However, if I move the the cached dir to an offline computer flair says file not found

### To Reproduce

```python
os.environ["TRANSFORMERS_OFFLINE"]="1"
os.environ["HF_DATASETS_OFFLINE"]="1"

flair_cache_root = pathlib.Path(__file__).parent.resolve() / 'models/.flair'

import flair
from flair.data import Sentence
from flair.nn import Classifier

flair.cache_root = flair_cache_root
print(flair.cache_root)

tagger_en = Classifier.load('flair/ner-english-large')
```

This works removing the transformers_online environment variable because the models are downloaded.

It still works if the variable is set, provided that the models had been downloaded to the same machine and location.

However, if I move the entire upper-level directory to an off-line machine, I receive an error message "File or directory not found".
```


### Expected behavior

I would like to be able to use Flair models on an offline machine. 


### Logs and Stack traces

_No response_

### Screenshots

_No response_

### Additional Context

_No response_

### Environment

The script does not work. It does not recognise true, false and null.

**Comment by helpmefindaname** [comment] 2023-12-01 15:23
closing this as it is a duplicate of https://github.com/flairNLP/flair/issues/3362

**Closed by helpmefindaname** 2023-12-01 15:23 UTC
Labels: bug
