### ISSUE TITLE
Text Classification - Loss function

### ISSUE THREAD

**Issue by bokstaller** [flairNLP/flair#2568] opened 2021-12-21 17:44 UTC
Hi everyone,

just a short question regarding loss functions. Is it possible to change the loss function when training the text classifier with flair? I would need to use the triplet loss.

Thanks in advance,

Jonas.

**Comment by whoisjones** [comment] 2021-12-21 18:53
Duplicate of #2567

**Closed** 2022-05-01 04:07 UTC
Labels: question, wontfix
